spring.application.name=rbac-auth-sys

spring.datasource.url=jdbc:mysql://localhost:3306/authSys_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=simpleRbacDemoSecretKeyForLearningPurposesOnly123456
jwt.expiration-ms=36000000